### PR TITLE
Fix hasMany relations saving

### PR DESCRIPTION
**Pull request by kitchenu**

### CODE REVIEW

**Comment by tuupola** [comment]
What is the bug this fixes?

**Comment by nebulousGirl** [comment]
Seems to fix a bug with saving hasMany relations that were deleted. Needs a test case though to ensure that the bug does not reappear in the future.

**Comment by vlucas** [comment]
@kitchenu Can you please update this PR with a test to demonstrate the new working behavior? We'd love to get this merged in.

**Comment by kitchenu** [comment]
I fixed testHasManyNewEntitySaveRelation() for #236

**Pull request merged**
